// Generated by CoffeeScript 1.4.0
(function() {
  "http://puzlet.com/puzlet/php/source.php?pageId=b00bj&file=d3.min.js";

  "b00fr";

  $blab.editorLinks({
    ode: {
      href: "/m/b00fr"
    },
    rk: {
      href: "/m/b00fr"
    }
  });

}).call(this);
